spring.application.name=backend
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_m879HhW7X

# ===============================
# CONFIGURACIÓN POSTGRESQL AWS
# ===============================
spring.datasource.url=jdbc:postgresql://pedidos360-db.czuikvgatgwo.us-east-1.rds.amazonaws.com:5432/pedidos360db
spring.datasource.username=admindb
spring.datasource.password=CloudNative2026!

# Hibernate: Crea o actualiza las tablas automáticamente basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true