spring.application.name=backend
server.port=8080

# URL del emisor (Issuer) de Cognito (Reemplaza us-east-1_Wteq89W6A con tu ID si es distinto)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_Wteq89W6A