name: 3. Backend Compile Pipeline

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/back-build.yml' # Agregado para que detecte este mismo cambio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permisos a Maven Wrapper (Fix para Windows)
        working-directory: ./backend
        run: chmod +x mvnw

      - name: Compilar con Maven
        working-directory: ./backend
        run: ./mvnw clean package -DskipTests